services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001" # IPFS swarm
      - "8080" # IPFS gateway
      - "5001" # IPFS API
    volumes:
      - ipfs_data:/data/ipfs
    restart: unless-stopped

  thumbs-up-http:
    image: amiller68/thumbs-up-http:latest
    ports:
      - "3000"
    volumes:
      - ./data:/app/data
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - LISTEN_PORT=3000
      - PEM_DATA_PATH=/app/data/pems
      - ALLOWED_AUDIENCES=leaky-server
    restart: unless-stopped

  # TODO: connect to the real deployed image
  leaky-server:
    image: amiller68/leaky-server:latest
    ports:
      - "3000"
    volumes:
      - ./data:/app/data
    environment:
      - LISTEN_ADDR=0.0.0.0:3000
      - SQLITE_DATABASE_URL=sqlite:///app/data/server.db
      - IPFS_RPC_URL=http://ipfs:5001
      - GET_CONTENT_FORWARDING_URL=https://leaky.krondor.org/content
    restart: unless-stopped

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=leaky.krondor.org
      - VALIDATION=http
      - CERTPROVIDER=letsencrypt
      - EMAIL=al@krondor.org
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

volumes:
  ipfs_data:

networks:
  default:
    name: swag_net
