version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"  # IPFS swarm
      - "8080:8080"  # IPFS gateway
      - "5001:5001"  # IPFS API
    volumes:
      - ipfs_data:/data/ipfs
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ipfs
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge

volumes:
  ipfs_data: