name: 🛡 Dependency Security & License Audit 
on:
  - pull_request

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        checks:
          # TODO: reenable advisories when i have time to explore the issues
          # - advisories
          - bans sources

    # Prevent sudden announcement of a new advisory from failing CI:
    # continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
        arguments: --all-features
